### ISSUE TITLE
[feature request] Support all available commands

### ISSUE THREAD

**Issue by kennymc-c** [unfoldedcircle/integration-denonavr#33]
### Description

This integration just has a very limited feature set of available commands. A/V receivers commonly have a lot of functions that can be controlled or set.
It would be great to control all of these with this integration. Please at least support all missing media player entity features like menu, dpad and sound mode.

**Comment by Cod053** [comment]
Agreed and seconded. We're missing a lot of stuff, not least the OPTION, INFO, and SETUP options, which are all quite essential.

**Comment by zehnm** [comment]
Added in PR #36 by @albaintor

**Comment by kennymc-c** [comment]
@zehnm While this PR implements the dpad and menu features there are still other functions that could be supported through simple commands like Monitor out and Display Dimmer.
Should I create a new issue for this or will you reopen this issue as this ticket is about all missing commands?

**Comment by zehnm** [comment]
The mentioned features in the issue description have been implemented. Also sound mode list was already implemented. With the updated denonavr library, more sounds modes should be available (https://github.com/ol-iver/denonavr/releases/tag/0.11.5).

Please open a new issue if you require other specific features.
